#!/bin/bash
# Script de démarrage de l'application ImageFlow Pro avec la fonctionnalité Cropping

# Configuration
PROJECT_PATH="c:\Users\Administrator\Documents\Institut\ING-2\Traitement-Image\App_Web_Image"

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║     ImageFlow Pro - Application de Traitement d'Images              ║"
echo "║         Avec nouvelle fonctionnalité: CROPPING                      ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""

# Vérification du répertoire
echo "[1/4] Vérification du répertoire..."
if [ ! -d "$PROJECT_PATH" ]; then
    echo "❌ Le répertoire n'existe pas: $PROJECT_PATH"
    exit 1
fi
echo "✅ Répertoire trouvé"
echo ""

# Navigation vers le répertoire
echo "[2/4] Navigation vers le répertoire du projet..."
cd "$PROJECT_PATH" || exit 1
echo "✅ Dans le répertoire: $(pwd)"
echo ""

# Démarrage du backend
echo "[3/4] Démarrage du backend (FastAPI)..."
echo "Commande: uv run uvicorn backend.app.main:app --reload"
echo "URL: http://localhost:8000"
echo "API Docs: http://localhost:8000/docs"
echo ""
echo "⏳ Le backend démarre dans 5 secondes..."
sleep 2

# Note pour l'utilisateur
echo ""
echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║ INSTRUCTIONS POUR DÉMARRER L'APPLICATION                           ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""
echo "🖥️  TERMINAL 1 - BACKEND (FastAPI)"
echo "────────────────────────────────────"
echo "Exécutez cette commande:"
echo ""
echo "    cd \"c:\\Users\\Administrator\\Documents\\Institut\\ING-2\\Traitement-Image\\App_Web_Image\""
echo "    uv run uvicorn backend.app.main:app --reload"
echo ""
echo "Attendez que le message s'affiche:"
echo "    ✅ Uvicorn running on http://127.0.0.1:8000"
echo ""
echo "Vous pouvez accéder à:"
echo "    • API Docs (Swagger): http://localhost:8000/docs"
echo "    • ReDoc: http://localhost:8000/redoc"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🌐 TERMINAL 2 - FRONTEND (Streamlit)"
echo "────────────────────────────────────"
echo "Exécutez cette commande:"
echo ""
echo "    cd \"c:\\Users\\Administrator\\Documents\\Institut\\ING-2\\Traitement-Image\\App_Web_Image\""
echo "    streamlit run frontend/app.py"
echo ""
echo "L'application s'ouvrira automatiquement à:"
echo "    http://localhost:8501"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 UTILISER LA NOUVELLE FONCTIONNALITÉ CROPPING"
echo "─────────────────────────────────────────────"
echo "1. Charger une image via le bouton de téléchargement"
echo "2. Cliquer sur l'onglet \"✂️ Cropping\" (2e onglet)"
echo "3. Ajuster les paramètres:"
echo "   • Sliders: Position X/Y, Largeur, Hauteur"
echo "   • Présets: Carré, 16:9, 9:16, 4:3"
echo "4. Prévisualiser le résultat (avant/après)"
echo "5. Cliquer \"✂️ Appliquer le Crop\""
echo "6. L'image est mise à jour et prête pour d'autres transformations"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🧪 TESTER L'API DIRECTEMENT"
echo "──────────────────────────"
echo "Vous pouvez tester l'endpoint /crop à partir de:"
echo ""
echo "1. Swagger UI (recommandé):"
echo "   http://localhost:8000/docs"
echo "   • Trouver l'endpoint POST /crop"
echo "   • Cliquer \"Try it out\""
echo "   • Charger une image et définir les paramètres"
echo ""
echo "2. Via curl (en PowerShell):"
echo "   $form = @{"
echo "     'file' = Get-Item 'path/to/image.png'"
echo "     'x' = '100'"
echo "     'y' = '50'"
echo "     'width' = '400'"
echo "     'height' = '300'"
echo "   }"
echo "   Invoke-RestMethod -Uri 'http://localhost:8000/api/crop' \"
echo "     -Method Post -Form $form -OutFile 'result.png'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 DOCUMENTATION"
echo "───────────────"
echo "Consultez les fichiers suivants pour plus d'informations:"
echo ""
echo "1. RESUME_CROPPING.md"
echo "   └─ Résumé complet des implémentations"
echo ""
echo "2. CROP_FEATURE.md"
echo "   └─ Documentation détaillée de la fonctionnalité"
echo ""
echo "3. TEST_CROPPING.md"
echo "   └─ Guide de test avec exemples"
echo ""
echo "4. ARCHITECTURE_CROPPING.md"
echo "   └─ Diagrammes d'architecture et flux de données"
echo ""
echo "5. EXEMPLE_VISUEL_CROPPING.md"
echo "   └─ Aperçu visuel de l'interface"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  DÉPANNAGE"
echo "───────────"
echo "Problème: \"Impossible de se connecter au backend\""
echo "Solution: Assurez-vous que le backend (uvicorn) est démarré sur le port 8000"
echo ""
echo "Problème: \"Module not found\""
echo "Solution: Assurez-vous d'avoir exécuté 'uv sync' et 'pip install -r requirements.txt'"
echo ""
echo "Problème: \"Address already in use\""
echo "Solution: Le port 8000 (ou 8501) est déjà utilisé."
echo "          Tuez le processus ou utilisez un port différent"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Prêt? Exécutez les commandes dans deux terminaux différents!"
echo ""
